### PR TITLE
Etcd v2 support

### PR DESCRIPTION
**Pull request by luispollo**
Hello @mindreframer, I did some work over the previous attempt to introduce support for the V2 API.

The tests all pass in my local environment with etcd 2.3.3, including the integration tests, however the heartbeat test has inconsistent results (which I don't think have anything to do with my changes).

Hope you'll be interested. Let me know if there's anything you don't like.

### CODE REVIEW

**Comment by mindreframer** [comment]
@luispollo that's great, thank you! I'm not actively programming in ruby + using Etcd-rb anymore, you should probably ask @iconara for write access.
I've merged this pull request, because any progress is better, that none :) 
If you're using Etcd-rb, consider adopting this library for the future. 

Best, 
Roman

**Comment by luispollo** [comment]
@mindreframer thanks a lot for merging the PR. We are currently running tests with the library in preparation to release in production. BTW, how do you feel about publishing the current version to rubygems? (On a side note, I forgot to bump up the gem version in my commits, sorry.)

**Comment by mindreframer** [comment]
@luispollo sorry for super-late response... this was low prio and I was swamped with life stuff... 

released to rubygems under version 1.1.0. I'm not sure how this gem is supposed to evolve further, @iconara is not responding and I have no rights to add other contributors / maintainers... 

Would you be up to develop it further? Maybe fork?

**Comment by luispollo** [comment]
@mindreframer My turn to apologize for the super-late response. :-)

We've been using the gem in prod for a little while without major issues. We do have a need to continue to add features to it (e.g. issue #17), so yeah, I think I'll consider using my fork going forward. How about pushing the gem to rubygems, though? I assume I'd need to rename the gem?

Thanks again for your help.

**Comment by mindreframer** [comment]
@luispollo I wrote an email to @iconara, maybe he will add you  to maintainers here... If he won't respond, well... Then fork and release under a new name... I am kinda helpless here...

**Comment by iconara** [comment]
@luispollo you should have an invite link in your mailbox now. Sorry for not responding earlier, I must have missed that you mentioned me in this thread.

**Comment by iconara** [comment]
@luispollo post your RubyGems username here and I'll add you as owner of the gem too.

**Comment by mindreframer** [comment]
@iconara thank you very much! ))

**Comment by luispollo** [comment]
Thanks @iconara. My RubyGems username is luisfpollo.

**Comment by iconara** [comment]
@luispollo you're now owner of the gem.

**Pull request merged**
